# Generated by Django 4.1.7 on 2023-03-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignments",
            options={"ordering": ["due_time"]},
        ),
        migrations.AddField(
            model_name="assignments",
            name="missed",
            field=models.BooleanField(default=False),
        ),
    ]
