# Generated by Django 4.1.7 on 2023-03-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0004_alter_assignments_options_assignments_missed"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignments",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assignments",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
