# Generated by Django 4.1.7 on 2023-03-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0005_assignments_date_assignments_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignments",
            name="date",
        ),
        migrations.RemoveField(
            model_name="assignments",
            name="time",
        ),
        migrations.AddField(
            model_name="assignments",
            name="date_str",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="assignments",
            name="time_str",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
